ulp-lua-objs := accept.o        \
                allocator.o     \
                close.o         \
                getsockopt.o    \
                module.o        \
                pool.o          \
                pretty.o        \
                recvmsg.o       \
                setsockopt.o    \

obj-m += ulp-lua.o
